"""init

Revision ID: 0f36e695a78c
Revises: 
Create Date: 2026-07-11 17:11:29.792261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0f36e695a78c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False, comment='审核内容原文'),
    sa.Column('content_type', sa.String(length=20), nullable=False, comment='内容类型: text / image'),
    sa.Column('review_dimension', sa.String(length=30), nullable=False, comment='审核维度'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='审核状态'),
    sa.Column('risk_level', sa.String(length=20), nullable=True, comment='风险等级'),
    sa.Column('l1_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='L1 关键词匹配结果'),
    sa.Column('l2_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='L2 RAG 法规检索结果'),
    sa.Column('l3_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='L3 LLM 判定结果'),
    sa.Column('review_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='最终审核结论'),
    sa.Column('degraded', sa.Boolean(), nullable=False, comment='是否降级运行'),
    sa.Column('skipped_layers', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='被跳过的检测层列表'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='降级/失败原因'),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True, comment='处理耗时（毫秒）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_review_records_created_at', 'review_records', ['created_at'], unique=False)
    op.create_index('ix_review_records_dimension', 'review_records', ['review_dimension'], unique=False)
    op.create_index('ix_review_records_risk_level', 'review_records', ['risk_level'], unique=False)
    op.create_index('ix_review_records_status', 'review_records', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_review_records_status', table_name='review_records')
    op.drop_index('ix_review_records_risk_level', table_name='review_records')
    op.drop_index('ix_review_records_dimension', table_name='review_records')
    op.drop_index('ix_review_records_created_at', table_name='review_records')
    op.drop_table('review_records')
    # ### end Alembic commands ###
